flyway.url=jdbc:postgresql://localhost:5432/sigebio
flyway.user=postgres
flyway.password=Ab12345678/
flyway.locations=filesystem:sql
flyway.schemas=sigebio,public
flyway.defaultSchema=sigebio
flyway.cleanDisabled=true